remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-midnight
title: pavlvs-91's homepage
description: Pawel Gleindek's page on GitHub

